services:
  - type: web
    name: evara-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false

staticSites:
  - name: evara-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://evara-backend.onrender.com
